//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int contactID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string companyName { get; set; }
        public string email { get; set; }
        public string message { get; set; }
    }
}
